server:
  port: 9801

# mybatis 配置
mybatis:
  type-aliases-package: wiki.laona.springcloud.pojo
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456


# Eureka 配置，服务注册
eureka:
  client:
    service-url:      # Eureka 监控页面
      defaultZone: http://localhost:9701/eureka/
  instance:
    instance-id: springcloud-provider-dept-9801   # 实例 id


# info 配置
info:
  app.name: springcloud
  company.name: blog.laona.wiki
